
import { Translations } from './types';

export const translations: Translations = {
  en: {
    title: 'Digital Mannequin AI',
    tagline: 'Virtual Try-On, Reimagined.',
    step1Title: 'Step 1: Upload Your Photo',
    step1Description: 'Upload a clear, full-body photo of yourself or a model.',
    uploadModel: 'Upload Model',
    step2Title: 'Step 2: Upload Clothing Photo',
    step2Description: 'Upload a photo of the garment on a plain background.',
    uploadClothing: 'Upload Garment',
    generateButton: 'Create Try-On',
    generating: 'Generating... this may take a moment.',
    resultTitle: 'Your Virtual Try-On',
    startOverButton: 'Start Over',
    errorTitle: 'An Error Occurred',
    errorDescription: 'Could not process the images. Please try again with different images.',
    dropOrClick: 'Drop image here or click to select',
    changeImage: 'Change Image',
    howToRunTitle: 'How to Run This Website',
    howToRunDescription: 'Follow these steps to run this project on your own computer.',
    howToRunStep1: '1. Prerequisites: Make sure you have Node.js and npm installed.',
    howToRunStep2: '2. Setup: Download the project files, open a terminal in the folder, and run `npm install`.',
    howToRunStep3: '3. API Key: The Gemini API key must be available as an environment variable named `API_KEY`. You must set this variable in your system before starting the application. For example: `export API_KEY="YOUR_API_KEY"` on Linux/macOS or `$env:API_KEY="YOUR_API_KEY"` on Windows PowerShell.',
    howToRunStep4: '4. Run: Start the development server by running `npm start`.',
    howToRunStep5: '5. View: Open `http://localhost:3000` (or the address shown in your terminal) in your web browser.',
  },
  fa: {
    title: 'مانکن دیجیتال هوشمند',
    tagline: 'پرو مجازی، به سبکی نوین.',
    step1Title: 'مرحله ۱: عکس خود را آپلود کنید',
    step1Description: 'یک عکس واضح و تمام قد از خودتان یا یک مدل آپلود کنید.',
    uploadModel: 'آپلود مدل',
    step2Title: 'مرحله ۲: عکس لباس را آپلود کنید',
    step2Description: 'یک عکس از لباس مورد نظر روی یک پس‌زمینه ساده آپلود کنید.',
    uploadClothing: 'آپلود لباس',
    generateButton: 'ایجاد پرو مجازی',
    generating: 'در حال ساخت... این فرآیند ممکن است کمی طول بکشد.',
    resultTitle: 'نتیجه پرو مجازی شما',
    startOverButton: 'شروع مجدد',
    errorTitle: 'خطایی رخ داد',
    errorDescription: 'پردازش تصاویر با مشکل مواجه شد. لطفاً با تصاویر دیگری امتحان کنید.',
    dropOrClick: 'عکس را اینجا رها کنید یا برای انتخاب کلیک کنید',
    changeImage: 'تغییر عکس',
    howToRunTitle: 'چگونه این وب‌سایت را اجرا کنیم',
    howToRunDescription: 'برای اجرای این پروژه روی کامپیوتر خود، مراحل زیر را دنبال کنید.',
    howToRunStep1: '۱. پیش‌نیازها: اطمینان حاصل کنید که Node.js و npm روی سیستم شما نصب شده باشد.',
    howToRunStep2: '۲. راه‌اندازی: فایل‌های پروژه را دانلود کنید، یک ترمینال در پوشه پروژه باز کرده و دستور `npm install` را اجرا کنید.',
    howToRunStep3: '۳. کلید API: کلید API Gemini باید به عنوان یک متغیر محیطی با نام `API_KEY` در دسترس باشد. قبل از اجرای برنامه باید این متغیر را در سیستم خود تنظیم کنید. به عنوان مثال: `export API_KEY="YOUR_API_KEY"` در لینوکس/مک یا `$env:API_KEY="YOUR_API_KEY"` در پاورشل ویندوز.',
    howToRunStep4: '۴. اجرا: با اجرای دستور `npm start` سرور توسعه را راه‌اندازی کنید.',
    howToRunStep5: '۵. مشاهده: آدرس `http://localhost:3000` (یا آدرسی که در ترمینال شما نمایش داده می‌شود) را در مرورگر وب خود باز کنید.',
  }
};
